// <auto-generated />
using System;
using Core.Infraestructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Core.Infraestructure.Persistance.Migrations
{
    [DbContext(typeof(FisiolabsSofwaredbContext))]
    partial class FisiolabsSofwaredbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Domain.Entities.Cita", b =>
                {
                    b.Property<int>("CitasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("CitasId");

                    b.HasIndex(new[] { "PacienteId" }, "paciente_id");

                    b.ToTable("citas", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Diagnostico", b =>
                {
                    b.Property<int>("DiagnosticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("Diagnostico1")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosticoFinal")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosticoFuncional")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosticoInicial")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosticoNosologico")
                        .HasColumnType("longtext");

                    b.Property<string>("DiagnosticoPrevio")
                        .HasColumnType("longtext");

                    b.Property<bool>("Estatus")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EstudiosComplementarios")
                        .HasColumnType("longtext");

                    b.Property<int>("ExpededienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FrecuenciaTratamiento")
                        .HasColumnType("longtext");

                    b.Property<string>("Inspeccion")
                        .HasColumnType("longtext");

                    b.Property<string>("MotivoAlta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Movibilidad")
                        .HasColumnType("longtext");

                    b.Property<string>("PadecimientoActual")
                        .HasColumnType("longtext");

                    b.Property<string>("Palpitacion")
                        .HasColumnType("longtext");

                    b.Property<string>("Refiere")
                        .HasColumnType("longtext");

                    b.Property<string>("TerapeuticaEmpleada")
                        .HasColumnType("longtext");

                    b.HasKey("DiagnosticoId");

                    b.HasIndex(new[] { "ExpededienteId" }, "expediente_id");

                    b.ToTable("diagnostico", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.EstadoCivil", b =>
                {
                    b.Property<int>("EstadoCivilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("EstadoCivil1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EstadoCivilId");

                    b.ToTable("estado_civil", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Expediente", b =>
                {
                    b.Property<int>("ExpedienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AntecedentesPatologicos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Responsable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TipoInterrogatorio")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ExpedienteId");

                    b.HasIndex(new[] { "PacienteId" }, "paciente_id")
                        .IsUnique()
                        .HasDatabaseName("paciente_id1");

                    b.ToTable("expediente", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.ExploracionFisica", b =>
                {
                    b.Property<int>("ExploracionFisicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<float?>("Estatura")
                        .HasColumnType("float");

                    b.Property<int?>("Fc")
                        .HasColumnType("int");

                    b.Property<int?>("Fr")
                        .HasColumnType("int");

                    b.Property<float?>("Imc")
                        .HasColumnType("float");

                    b.Property<float?>("IndiceCinturaCadera")
                        .HasColumnType("float");

                    b.Property<float?>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("PresionArterial")
                        .HasColumnType("longtext");

                    b.Property<float?>("SaturacionOxigeno")
                        .HasColumnType("float");

                    b.Property<float?>("Temperatura")
                        .HasColumnType("float");

                    b.HasKey("ExploracionFisicaId");

                    b.HasIndex(new[] { "DiagnosticoId" }, "diagnostico_id");

                    b.ToTable("exploracion_fisica", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Fisioterapeutum", b =>
                {
                    b.Property<int>("FisioterapeutaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fisioterapeuta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FisioterapeutaId");

                    b.ToTable("fisioterapeuta", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.FlujoVaginal", b =>
                {
                    b.Property<int>("FlujoVaginalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Flujo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FlujoVaginalId");

                    b.ToTable("flujo_vaginal", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.GinecoObstetrico", b =>
                {
                    b.Property<int>("GinecoObstetricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Abortos")
                        .HasColumnType("int");

                    b.Property<int?>("Cesareas")
                        .HasColumnType("int");

                    b.Property<string>("Cirugias")
                        .HasColumnType("longtext");

                    b.Property<int?>("EdadGestional")
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<int?>("FlujoVaginalId")
                        .HasColumnType("int");

                    b.Property<string>("Fpp")
                        .HasColumnType("longtext");

                    b.Property<string>("Fum")
                        .HasColumnType("longtext");

                    b.Property<int?>("Gestas")
                        .HasColumnType("int");

                    b.Property<string>("Menarca")
                        .HasColumnType("longtext");

                    b.Property<int?>("Partos")
                        .HasColumnType("int");

                    b.Property<string>("Ritmo")
                        .HasColumnType("longtext");

                    b.Property<int?>("Semanas")
                        .HasColumnType("int");

                    b.Property<int?>("TipoAnticonceptivoId")
                        .HasColumnType("int");

                    b.HasKey("GinecoObstetricoId");

                    b.HasIndex(new[] { "ExpedienteId" }, "expediente_id")
                        .IsUnique()
                        .HasDatabaseName("expediente_id1");

                    b.HasIndex(new[] { "FlujoVaginalId" }, "flujo_vaginal_id");

                    b.HasIndex(new[] { "TipoAnticonceptivoId" }, "tipo_anticonceptivo_id");

                    b.ToTable("gineco_obstetrico", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.HeredoFamiliar", b =>
                {
                    b.Property<int>("HeredoFamiliarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Alcoholismo")
                        .HasColumnType("longtext");

                    b.Property<string>("Cancer")
                        .HasColumnType("longtext");

                    b.Property<string>("Dm")
                        .HasColumnType("longtext");

                    b.Property<string>("Drogas")
                        .HasColumnType("longtext");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<int>("Hermanos")
                        .HasColumnType("int");

                    b.Property<string>("HermanosCausaMuerte")
                        .HasColumnType("longtext");

                    b.Property<int>("HermanosVivos")
                        .HasColumnType("int");

                    b.Property<int>("Hijos")
                        .HasColumnType("int");

                    b.Property<string>("HijosCausaMuerte")
                        .HasColumnType("longtext");

                    b.Property<int>("HijosVivos")
                        .HasColumnType("int");

                    b.Property<string>("Hta")
                        .HasColumnType("longtext");

                    b.Property<int>("Padres")
                        .HasColumnType("int");

                    b.Property<string>("PadresCausaMuerte")
                        .HasColumnType("longtext");

                    b.Property<int>("PadresVivos")
                        .HasColumnType("int");

                    b.Property<string>("Tabaquismo")
                        .HasColumnType("longtext");

                    b.HasKey("HeredoFamiliarId");

                    b.HasIndex(new[] { "ExpedienteId" }, "expediente_id")
                        .IsUnique()
                        .HasDatabaseName("expediente_id2");

                    b.ToTable("heredo_familiar", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.MapaCorporal", b =>
                {
                    b.Property<int>("MapaCorporalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("RangoDolor")
                        .HasColumnType("int");

                    b.Property<int>("ValorX")
                        .HasColumnType("int");

                    b.Property<int>("ValorY")
                        .HasColumnType("int");

                    b.HasKey("MapaCorporalId");

                    b.HasIndex(new[] { "DiagnosticoId" }, "diagnostico_id")
                        .HasDatabaseName("diagnostico_id1");

                    b.ToTable("mapa_corporal", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.NoPatologico", b =>
                {
                    b.Property<int>("NoPatologicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ExpedienteId")
                        .HasColumnType("int");

                    b.Property<string>("MedioFisicoambiental")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MedioLaboral")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MedioSociocultural")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NoPatologicoId");

                    b.HasIndex(new[] { "ExpedienteId" }, "expediente_id")
                        .IsUnique()
                        .HasDatabaseName("expediente_id3");

                    b.ToTable("no_patologico", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApellidoCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("Domicilio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Edad")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EstadoCivilId")
                        .HasColumnType("int");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext");

                    b.Property<string>("Ocupacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Sexo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PacienteId");

                    b.HasIndex(new[] { "EstadoCivilId" }, "estado_civil_id");

                    b.ToTable("paciente", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.ProgramaFisioterapeutico", b =>
                {
                    b.Property<int>("ProgramaFisioterapeuticoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CortoPlazo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<string>("LargoPlazo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MedianoPlazo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pronostico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sugerencias")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TratamientoFisioterapeutico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ProgramaFisioterapeuticoId");

                    b.HasIndex(new[] { "DiagnosticoId" }, "diagnostico_id")
                        .HasDatabaseName("diagnostico_id2");

                    b.ToTable("programa_fisioterapeutico", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Revision", b =>
                {
                    b.Property<int>("RevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiagnosticoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FisioterapeutaId")
                        .HasColumnType("int");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RevisionId");

                    b.HasIndex(new[] { "DiagnosticoId" }, "diagnostico_id")
                        .HasDatabaseName("diagnostico_id3");

                    b.HasIndex(new[] { "FisioterapeutaId" }, "fisioterapeuta_id");

                    b.ToTable("revision", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.TipoAnticonceptivo", b =>
                {
                    b.Property<int>("TipoAnticonceptivoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Anticonceptivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TipoAnticonceptivoId");

                    b.ToTable("tipo_anticonceptivo", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Correo")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Especialidad")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidad")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Core.Domain.Entities.Cita", b =>
                {
                    b.HasOne("Core.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("citas_ibfk_1");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Core.Domain.Entities.Diagnostico", b =>
                {
                    b.HasOne("Core.Domain.Entities.Expediente", "Expedediente")
                        .WithMany("Diagnosticos")
                        .HasForeignKey("ExpededienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("diagnostico_ibfk_1");

                    b.Navigation("Expedediente");
                });

            modelBuilder.Entity("Core.Domain.Entities.Expediente", b =>
                {
                    b.HasOne("Core.Domain.Entities.Paciente", "paciente")
                        .WithMany("Expedientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("expediente_ibfk_1");

                    b.Navigation("paciente");
                });

            modelBuilder.Entity("Core.Domain.Entities.ExploracionFisica", b =>
                {
                    b.HasOne("Core.Domain.Entities.Diagnostico", "Diagnostico")
                        .WithMany("ExploracionFisicas")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("exploracion_fisica_ibfk_1");

                    b.Navigation("Diagnostico");
                });

            modelBuilder.Entity("Core.Domain.Entities.GinecoObstetrico", b =>
                {
                    b.HasOne("Core.Domain.Entities.Expediente", "Expediente")
                        .WithMany("GinecoObstetricos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("gineco_obstetrico_ibfk_3");

                    b.HasOne("Core.Domain.Entities.FlujoVaginal", "FlujoVaginal")
                        .WithMany("GinecoObstetricos")
                        .HasForeignKey("FlujoVaginalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("gineco_obstetrico_ibfk_1");

                    b.HasOne("Core.Domain.Entities.TipoAnticonceptivo", "TipoAnticonceptivo")
                        .WithMany("GinecoObstetricos")
                        .HasForeignKey("TipoAnticonceptivoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("gineco_obstetrico_ibfk_2");

                    b.Navigation("Expediente");

                    b.Navigation("FlujoVaginal");

                    b.Navigation("TipoAnticonceptivo");
                });

            modelBuilder.Entity("Core.Domain.Entities.HeredoFamiliar", b =>
                {
                    b.HasOne("Core.Domain.Entities.Expediente", "Expediente")
                        .WithMany("HeredoFamiliars")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("heredo_familiar_ibfk_1");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Core.Domain.Entities.MapaCorporal", b =>
                {
                    b.HasOne("Core.Domain.Entities.Diagnostico", "Diagnostico")
                        .WithMany("MapaCorporals")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("mapa_corporal_ibfk_1");

                    b.Navigation("Diagnostico");
                });

            modelBuilder.Entity("Core.Domain.Entities.NoPatologico", b =>
                {
                    b.HasOne("Core.Domain.Entities.Expediente", "Expediente")
                        .WithMany("NoPatologicos")
                        .HasForeignKey("ExpedienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("no_patologico_ibfk_1");

                    b.Navigation("Expediente");
                });

            modelBuilder.Entity("Core.Domain.Entities.Paciente", b =>
                {
                    b.HasOne("Core.Domain.Entities.EstadoCivil", "EstadoCivil")
                        .WithMany("Pacientes")
                        .HasForeignKey("EstadoCivilId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("paciente_ibfk_1");

                    b.Navigation("EstadoCivil");
                });

            modelBuilder.Entity("Core.Domain.Entities.ProgramaFisioterapeutico", b =>
                {
                    b.HasOne("Core.Domain.Entities.Diagnostico", "Diagnostico")
                        .WithMany("ProgramaFisioterapeuticos")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("programa_fisioterapeutico_ibfk_1");

                    b.Navigation("Diagnostico");
                });

            modelBuilder.Entity("Core.Domain.Entities.Revision", b =>
                {
                    b.HasOne("Core.Domain.Entities.Diagnostico", "Diagnostico")
                        .WithMany("Revisions")
                        .HasForeignKey("DiagnosticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("revision_ibfk_2");

                    b.HasOne("Core.Domain.Entities.Fisioterapeutum", "Fisioterapeuta")
                        .WithMany("Revisions")
                        .HasForeignKey("FisioterapeutaId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("revision_ibfk_1");

                    b.Navigation("Diagnostico");

                    b.Navigation("Fisioterapeuta");
                });

            modelBuilder.Entity("Core.Domain.Entities.Diagnostico", b =>
                {
                    b.Navigation("ExploracionFisicas");

                    b.Navigation("MapaCorporals");

                    b.Navigation("ProgramaFisioterapeuticos");

                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Core.Domain.Entities.EstadoCivil", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("Core.Domain.Entities.Expediente", b =>
                {
                    b.Navigation("Diagnosticos");

                    b.Navigation("GinecoObstetricos");

                    b.Navigation("HeredoFamiliars");

                    b.Navigation("NoPatologicos");
                });

            modelBuilder.Entity("Core.Domain.Entities.Fisioterapeutum", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Core.Domain.Entities.FlujoVaginal", b =>
                {
                    b.Navigation("GinecoObstetricos");
                });

            modelBuilder.Entity("Core.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("Expedientes");
                });

            modelBuilder.Entity("Core.Domain.Entities.TipoAnticonceptivo", b =>
                {
                    b.Navigation("GinecoObstetricos");
                });
#pragma warning restore 612, 618
        }
    }
}
